#!/bin/sh
# Give a battery name (e.g. BAT0) as an argument.

# get xresources colors
for x in "$(xrdb -query | grep color | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done

case $BLOCK_BUTTON in
    3) pgrep -x dunst >/dev/null 
esac

capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)

if [ "$capacity" -ge 100 ]; then
	color=""
elif [ "$capacity" -ge 75 ]; then
	color=""
elif [ "$capacity" -ge 50 ]; then
	color=""
elif [ "$capacity" -ge 25 ]; then
	color=""
elif [ "$capacity" -ge 15 ]; then
	color=""
fi

echo "$(echo "$status" | sed -e "s/,//;s/Discharging//;s/Not Charging//;s/Charging//;s/Unknown//;s/Full//;s/ 0*/ /g;s/ :/ /g")" "$color"  "$(echo "$capacity" | sed -e 's/$/%/')"
